### PR TITLE
[todo-mvvm-databinding_newarch] New branch which uses new android arch components

### PR DESCRIPTION
**Pull request by fastestdevalive**
New branch: **todo-mvvm-databinding_newarch**
I have made an attempt to integrate the new arch components into the todo-mvvm-databinding. So, all the ViewModels now extend `android.arch.lifecycle.ViewModel`.
The original plan was to remove the Observables all together and use LiveData only but it came out that Livedata doesnt support databinding as of now. 

- So all the observables which were interacting with data-binding are still as is.
- The snackbarText is implemented using LiveData
- All the @Bindable methods are now removed and are instead implemented as Observables (only for now). Once the android lifecycle hits 1.0 stable api we can remove all the observables and use LiveData only.
- Next, I would want to integrate the `android.arch.persistence.room` for Tasks storage.

### CODE REVIEW

**Comment by JoseAlcerreca** [comment]
The two main problems I see here are:
 - Injecting a navigator into the VM, which is an Activity
 - Snackbar will show everytime there's a config change (like rotation)

**Comment by JoseAlcerreca** [comment]
Also, TaskItemViewModel in TasksAdapter is not an arch components ViewModel (which is tricky).

**Comment by fastestdevalive** [comment]
What could be a good pattern for the snackbarText then?
- I can either skip the LiveData and go to the old way of the snackbarText but that will again bring in the onPropertyChangeCallback removal stuff in onDestroy of View components.
- If I stick to the LiveData, I can remember the last snackbarText unique on may be the taskID so that it doesn't get shown again.
- Since the LifeCycle API is still in beta. We can post an issue there so that they bring in the flexibility to opt in/out of the **instant** onChange callback on the Observer which LiveData calls. I think it might be useful.
@JoseAlcerreca Whats your take on this?

**Comment by fastestdevalive** [comment]
@JoseAlcerreca I tried solving injection of Navigator (an activity) into the VM problem. For now I have made changes in the `TaskDetail` part of the app. Let me know what you think on [this commit](https://github.com/gaurav414u/android-architecture/commit/26cb1d63948a52726681fdc33f82f447948a5aa2).
Just to give you an overview:
- Theres a base `NavigatingActivity` which is a LifeCycleRegistryOwner and also keeps the navigator as a generic type but defers the instantiation to the subclasses.
- `TaskDetailActivity` provides the instance of type `TaskDetailNavigatorImpl` which handles all the navigation callbacks and also listens for the activity's lifecycle
- In case the activity is destroyed `TaskDetailNavigatorImpl` will remove the navigator from the underlying `NavigatingActivity` in our case `TaskDetailActivity` which also removes the navigator from the `TaskDetailViewModel`

**Comment by fastestdevalive** [comment]
@JoseAlcerreca any updates?

**Comment by JoseAlcerreca** [comment]
Yes, see the new dev-todo-mvvm-live branch.

**Comment by fastestdevalive** [comment]
@JoseAlcerreca Thanks for the update. The implementation looks good and as expected. I will close this pull request.
Its interesting to see how you have made custom MutableLiveData with only new updates support. This solves both of the problems.

**Pull request closed without merging**
